# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flask:
    image: metabsd/flask-learning
    restart: always
    ports:
      - 5000:5000
